### ISSUE TITLE
Mac Installation Instructions

### ISSUE THREAD

**Issue by Nacheen81** [kakaroto/SWParser#10]
In the installation instructions for Mac users.  Under the "setup.py install" an additional note about using "python setup.py install" would be very helpful for some users.  I ran into this issues personally.  Using Mac OS 10.10.5 with Python 2.7.11 installed.  Sorry if this is the wrong place to submit this.  First time posting in GitHub.

**Comment by kakaroto** [comment]
Yeah, this is the right place to submit this kind of thing. I need to update the README, because the setup.py install isn't actually needed if you run from source. If I get the time, I might make it into a normal click-to-run app.

**Comment by Nacheen81** [comment]
Cool. Thanks for all the effort you put into it so us programming illiterate can have awesome things.
